title: Xu Zhao's Homepage
page-top-title: Xu Zhao
top-section-bg-text: Game Theory, Artificial Intelligence
home-subtitle: Xu Zhao&ensp;|&ensp;赵旭
copyright-text: '&copy; Xu Zhao 2023-2026. All Rights Reserved.'
